### ISSUE TITLE
Please update pypi `pytest-localserver` page

### ISSUE THREAD

**Issue by kloczek** [pytest-dev/pytest-localserver#1]
https://pypi.org/project/pytest-localserver/ still points to bitbucket :)

**Comment by diazona** [comment]
There's nothing I can do about that. You'd have to contact the owner of the pytest-localserver name (@redtoad) to get changes made on PyPI.

**Comment by diazona** [comment]
I'll reopen this now that we've gotten permissions straightened out with @redtoad. We will update the PyPI page soon!

**Comment by kloczek** [comment]
If you want me to test some PR/patch before commit please let me know :)

**Comment by diazona** [comment]
Absolutely, thanks! I think at this point the only thing holding this up is the updated certificate (#2) and any other crucial changes that we may want to build into a release, so if you think there's anything else that particularly needs to be done before publishing the next version on PyPI, please do let us know.

We're also dealing with some "growing pains" of the project - the three of us maintainers have to figure out how best to work together and not step on each others' toes. So I'm taking it a little slow. But I'm sure we can make a new release and update PyPI within a few days.

**Comment by diazona** [comment]
I just pushed the new version to PyPI so you should be all set now. Thanks for your involvement @kloczek! Let us know if you find any issues with the new version. (It's a small package, I figured the automated tests would be enough to make it safe to release, hopefully I don't come to regret that :smile: )
