### ISSUE TITLE
Module smtpd marked deprecated in Python 3.10

### ISSUE THREAD

**Issue by redtoad** [pytest-dev/pytest-localserver#12]
Apparently the SMTP module used in `pytest_loclaserver/smtp.py` will be deprecated in Python version 3.10. 

```
.tox/py310/lib/python3.10/site-packages/pytest_localserver/smtp.py:12
  /home/runner/work/pytest-localserver/pytest-localserver/.tox/py310/lib/python3.10/site-packages/pytest_localserver/smtp.py:12: DeprecationWarning: The smtpd module is deprecated and unmaintained.  Please see aiosmtpd (https://aiosmtpd.readthedocs.io/) for the recommended replacement.
    import smtpd
```
https://github.com/redtoad/pytest-localserver/runs/4191982788?check_suite_focus=true#step:5:218

Suggested replacement:
https://aiosmtpd.readthedocs.io/

**Comment by diazona** [comment]
Cool :+1: Given that aiosmtpd requires Python 3.6, which is the earliest supported version anyway, I'm thinking it makes sense to officially drop support for Python versions before 3.6 in our 0.6.0 release. Then hopefully the switch shouldn't be hard.

**Comment by diazona** [comment]
Oooh, you know what, I forgot about this when preparing #25, and I left Python 3.5 as a supported version. So I guess we have to either drop support for Python 3.5 as well, as part of the 0.6.0 release, or we could defer this change to a later version. (Or we could write the code in a way that uses smtpd on Python 3.5 and aiosmtpd on higher versions.)

Personally, I don't care which way we go. I'm sure we can have multiple releases of this package before Python 3.11 comes out. If I had to choose right now, I'd probably feel like deferring this just out of laziness :laughing: but that's not a smart way to make decisions....

@coordt FYI

**Comment by diazona** [comment]
Turns out I found a way to support Python 3.5 using aiosmtpd 1.2. It's kind of messy, but the work is done anyway :laughing:
