### ISSUE TITLE
Relax pytest requirements in tox

### ISSUE THREAD

**Issue by rominf** [pytest-dev/pytest-localserver#41]
I'm Fedora maintainer of `python-pytest-localsever`.

Fedora 37 uses `python3==3.11.0b3` and `pytest==7.1.2`, so I had to apply the patch to remove `pytest<7` requirement. It looks like all tests pass. Please, consider allowing `pytest>=7` for Python 3.11.

Also, Fedora 35 uses `pytest==6.2.4`, and in tox it's `pytest>=6.2.5`. I believe that patch version shouldn't matter. Please, consider allowing `pytest>=6.2.4` for Python 3.10.

**Comment by diazona** [comment]
Dropping the `pytest <7` requirement is definitely fine with me, and I'm also fine with relaxing the patch level requirement if there isn't a reason for it. Ideally I'd like to hear from @redtoad about whether he had a reason for adding those version constraints.

**Comment by redtoad** [comment]
> Ideally I'd like to hear from @redtoad about whether he had a reason for adding those version constraints.
You give me too much credit here by assuming I had a rational reason for doing so. If I remember correctly, this was done by trial and error.

**Comment by diazona** [comment]
Fair enough!
