### ISSUE TITLE
Set up automated testing

### ISSUE THREAD

**Issue by diazona** [pytest-dev/pytest-localserver#5]
I'd like to set up automated testing, with Github Actions or Travis or whatever makes sense.

I have not done this on Github before, so I'm happy to have someone with more familiarity do it, but if not I wouldn't mind taking it on as a learning experience.

**Comment by diazona** [comment]
Huh I'm not sure what triggered this to get closed

**Comment by redtoad** [comment]
> Huh I'm not sure what triggered this to get closed

I went a bit crazy with linking PRs. That probably had something to do with it.
