### ISSUE TITLE
With deprecation of smtpd module, are you going to vendor the module?

### ISSUE THREAD

**Issue by rouilj** [pytest-dev/pytest-localserver#51]
It looks like smtpd has been deprecated since 3.6: https://docs.python.org/3/library/smtpd.html
and is going to be removed in 3.12.  Are you planning on vendoring smtpd or changing to aiosmtpd?

Thanks.

- rouilj
-

**Comment by diazona** [comment]
I believe that was already done in #30, wasn't it? We switched to aiosmtpd, although that package is apparently unmaintained as well so it's unclear if we will be keeping SMTP support at all in the long term.

**Comment by rouilj** [comment]
Ah, ok. I have a use case for the smtpd module when testing the [Roundup Issue Tracker](https://www.roundup-tracker.org). The Readme.rst still references the smtpd module hence
my posting the issue.

**Comment by diazona** [comment]
Ah I see, makes sense. Well the discrepancy in the README is still something that should be fixed, so thanks for pointing that out! I'd be happy to merge a pull request for that if you want to make one, otherwise I'll probably get around to it sometime next month.

**Comment by diazona** [comment]
Let me actually reopen this, since it looks like I never got around to doing that documentation update - I probably forgot since this wasn't in the list of open issues.
