### ISSUE TITLE
Enabling pre-commit.ci

### ISSUE THREAD

**Issue by diazona** [pytest-dev/pytest-localserver#79]
I looked into enabling [pre-commit.ci](https://pre-commit.ci) on this repo, but I wasn't sure about the right way to follow the installation flow while ensuring that the app isn't removed from other pytest-dev repositories using it. Could one of the organization owners who's more familiar with the process help out? (@nicoddemus perhaps?)

![Installation dialog for pre-commit.ci](https://github.com/pytest-dev/pytest-localserver/assets/615345/68a24a53-e6a3-47b0-9fa5-3ea631ae42d9)

**Comment by RonnyPfannschmidt** [comment]
i just enabled it, it woudl have been fine if you just did that as well :+1:

**Comment by diazona** [comment]
Thanks! I just couldn't tell from the interface whether I might accidentally disable it for other projects if I didn't make the right selections.
