### ISSUE TITLE
Update changelog for v0.5.1

### ISSUE THREAD

**Issue by diazona** [pytest-dev/pytest-localserver#9]
This is so we don't forget to update the changelog before releasing the next version to PyPI.

BTW I keep calling it v0.5.1 since it seems like basically a patch release compared to the current v0.5.0, with the only real functional difference being the new certificate, but that's just me - if y'all want to jump ahead to v0.6 or something, let's discuss.

**Comment by redtoad** [comment]
I support 0.5.1 since nothing inherently new was added.
